window.$           = require 'jquery'
window._           = require 'underscore'
window.Backbone    = require 'backbone'
window.Marionette  = require 'backbone.marionette'
window.Handlebars  = require 'handlebars'
